server:
  port: 8080

eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: config-server
  cloud: 
    config:
      name: config-server
      server: 
        git: 
          uri: https://github.com/Hyphalosaurus-Pocket/SpringCloudDemo.git
          username: 
          password: 
          searchPaths: '{profile}'
      
          


